<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Resend_r4vIwl _5BVqVB BVDqf_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>1293dd5e-93c1-49ea-8ebf-a4107eef6939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='169235']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a096fd09-3d05-4729-8b50-e9ff5b9d0687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>56e1181e-fba8-4c32-8900-7526370b7c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>ccd5b7bf-57b6-4dd6-b1dc-f6d1d7f35ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e59f5a4-bf14-46cb-987a-fb5082693758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>r4vIwl _5BVqVB BV+Dqf</value>
      <webElementGuid>d86bcde0-0258-41dd-be92-5566755cc7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>169235</value>
      <webElementGuid>c358f870-0a9f-441f-9c30-eceffeb49393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;VCR99n&quot;]/div[@class=&quot;NXna7w row wjcbtA&quot;]/div[@class=&quot;Sm1-5F col col-3-5&quot;]/div[1]/form[1]/div[@class=&quot;I-qZ4M vLRlQb&quot;]/input[@class=&quot;r4vIwl _5BVqVB BV+Dqf&quot;]</value>
      <webElementGuid>ff57cebb-c1c8-4b21-8c9e-84fbb51b78d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='169235']</value>
      <webElementGuid>189d8b0f-e9f1-49e7-8afc-8193b3742f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div/form/div[3]/input</value>
      <webElementGuid>ecd82491-9272-47bb-b49c-f9208fb6a82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>173e3723-df7b-4d7c-a54b-dd1ffd8bc9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>af6b739c-866f-46c4-a345-6908fdbdbdcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
