<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Resend_r4vIwl _5BVqVB BVDqf_1_2</name>
   <tag></tag>
   <elementGuidId>3f6d3baf-1ed0-4ca0-8c42-8900056302e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='169']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ee6accb-ad85-45bc-8784-5166290f7d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>4a3c3c33-2c7f-48ae-8432-d7727e7f4683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>209568b7-ea00-4580-ae03-62e93fff81d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69ce7942-e674-499e-ad74-0fa80c8e6e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>r4vIwl _5BVqVB BV+Dqf</value>
      <webElementGuid>3c6325a8-9fb7-47c3-a1d3-4232bde867b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>169</value>
      <webElementGuid>bbb9aa5a-4492-4998-a168-601d9941b5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;VCR99n&quot;]/div[@class=&quot;NXna7w row wjcbtA&quot;]/div[@class=&quot;Sm1-5F col col-3-5&quot;]/div[1]/form[1]/div[@class=&quot;I-qZ4M vLRlQb&quot;]/input[@class=&quot;r4vIwl _5BVqVB BV+Dqf&quot;]</value>
      <webElementGuid>4d6584e9-aecf-4cbd-b313-f4251fe25aa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='169']</value>
      <webElementGuid>8cf940ff-3026-4044-9a8b-4b3d9cd2cc1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div/form/div[3]/input</value>
      <webElementGuid>282a0bd1-deec-4f48-8ac0-d2d560d953d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>9027f9f3-a439-45fe-ad27-e6f0038ea4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>3b0a96ef-db59-4385-943f-309fba2ee700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
