<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All Leave</name>
   <tag></tag>
   <elementGuidId>eb027b0b-f3b6-411a-bad2-4ded0ace8227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9a53393-f28f-4294-8575-6a86f1503a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>d55cb957-d0c8-4f18-9eb8-6dc17263d784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d8d23b22-6c33-4b75-95ec-ce195cdc5154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX</value>
      <webElementGuid>6612f576-c7c6-448a-b8e1-1c5fdf2c9a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comm-navigation__top-level-item-link js-top-level-menu-item linkBtn</value>
      <webElementGuid>65c7bb46-dcd6-46fb-bd32-c0b43ec76f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>30:135;a</value>
      <webElementGuid>fcd6e410-6f0b-4016-998d-d78646487992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Leave</value>
      <webElementGuid>21e4e9c2-8328-43e5-8ea3-a3dc4a5d1f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5&quot;)</value>
      <webElementGuid>37e8af9b-4ba9-49a4-99a7-fd9e71401dd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='5']</value>
      <webElementGuid>b16ddba6-928a-4ddd-a680-41dd42491b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commThemeNav']/div/div/nav/ul/li[6]/a</value>
      <webElementGuid>4cec7649-505c-4426-a284-eca7d1e57a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'All Leave')]</value>
      <webElementGuid>0905ac8a-41a6-4db5-9831-fa3e37128e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Leave'])[1]/following::a[1]</value>
      <webElementGuid>2b7a7338-2073-4ce1-8de5-0de5e297aeb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Attendance Records'])[1]/following::a[2]</value>
      <webElementGuid>82f86c01-5e90-45a3-8853-4f8f0601b5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Engagements'])[1]/preceding::a[1]</value>
      <webElementGuid>8e409445-ebd4-4b10-a9cc-248df25cb359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Allocations'])[1]/preceding::a[2]</value>
      <webElementGuid>e528642f-8d04-4966-9649-d4e3106220d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Leave']/parent::*</value>
      <webElementGuid>cd46b071-479c-47ee-9b7c-363a188cc419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX')]</value>
      <webElementGuid>fe1482bd-7104-4cb6-ae28-dec6de561033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>fa5776ad-3cdc-4b0d-b878-f1193cb72076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '5' and @href = '/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX' and (text() = 'All Leave' or . = 'All Leave')]</value>
      <webElementGuid>aa23fb69-2db6-417f-b1a6-2f78f4277953</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
