<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name on Card_nameOnCard</name>
   <tag></tag>
   <elementGuidId>dfdac28c-4eb4-40b3-9840-9c6dbc3746ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nameOnCard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nameOnCard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7567765-2bda-4055-91fb-89f3a054fc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7455311-ff7a-48c8-9084-4039c17ae4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nameOnCard</value>
      <webElementGuid>31d250a6-5977-49bf-b2a3-6f77546c0860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>John Smith</value>
      <webElementGuid>96a4cb6f-1544-49e6-be94-2430cc2e3c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameOnCard</value>
      <webElementGuid>0f857d7d-5191-47cd-81ec-b0743c7012df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nameOnCard&quot;)</value>
      <webElementGuid>72d08e2c-38bc-4fd2-a9ae-8664cd539155</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nameOnCard']</value>
      <webElementGuid>a3cfe3a9-0611-4714-b663-aefe0c52b417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>81e0524e-295f-46da-99d8-8dd36c4e7ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nameOnCard' and @placeholder = 'John Smith' and @name = 'nameOnCard']</value>
      <webElementGuid>bd877237-6795-4efe-946b-e693d05b9ea3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
