<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All Leave</name>
   <tag></tag>
   <elementGuidId>fca77eb6-9c23-4576-b930-175b6870b2b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe2cbf6d-54cd-4ec8-9dd4-5380809bf6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>20ce980e-9b05-4f4f-b181-aa51fe0f10c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>eb1b6ac9-a497-4072-b252-d9c3e3c1987f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX</value>
      <webElementGuid>6fa590b1-3192-465e-b7e3-04d6f04c163a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comm-navigation__top-level-item-link js-top-level-menu-item linkBtn</value>
      <webElementGuid>f477999e-25d5-40f0-a063-df5209f74e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>30:147;a</value>
      <webElementGuid>388eb6c5-f33c-469c-91e2-aba774b08b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Leave</value>
      <webElementGuid>419203c0-95c4-49a6-8358-515a1b4e89c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5&quot;)</value>
      <webElementGuid>e96a4652-7c31-4fde-a7cd-d82b89f91546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='5']</value>
      <webElementGuid>288e8dc7-fd9b-43fc-85ca-c867478eb62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commThemeNav']/div/div/nav/ul/li[6]/a</value>
      <webElementGuid>150d0068-fef0-40c8-abaa-3b6a5a0b7272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'All Leave')]</value>
      <webElementGuid>1741c6ec-6f79-4a3b-8b66-410b5d0a8936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Leave'])[1]/following::a[1]</value>
      <webElementGuid>cf6a4622-ecd3-4eae-99b6-b7ae5393a744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Attendance Records'])[1]/following::a[2]</value>
      <webElementGuid>7f09728f-b380-430a-819f-be6ce0a4c84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Engagements'])[1]/preceding::a[1]</value>
      <webElementGuid>f5119932-f650-43a4-a28d-39b5f0d0ce74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Allocations'])[1]/preceding::a[2]</value>
      <webElementGuid>875b932f-68be-4ca3-ad51-7a6d7eae4674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Leave']/parent::*</value>
      <webElementGuid>faccf880-66cf-4837-847a-91100c3cfe33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX')]</value>
      <webElementGuid>1e79c035-55dd-420f-8d5b-c8d2ca599388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>5083a042-32d0-4d6b-b1b0-da9b1afae362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '5' and @href = '/CRMITCommunity/s/employee-leave/Employee_Leave__c/00B1K00000ANF4IUAX' and (text() = 'All Leave' or . = 'All Leave')]</value>
      <webElementGuid>60497065-cc74-41a1-9c2f-bb86f31ead16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
