<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SelectedAll</name>
   <tag></tag>
   <elementGuidId>715d471e-bc11-4377-b76c-c54a14f6f3c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.slds-dropdown__item.has-icon--left.forceVirtualAutocompleteMenuOption > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='virtualAutocompleteListbox_7c1887c26ee74']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70420041-0391-47a6-bf7c-b852bb1003e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bfaace15-623d-4106-a262-a80af7ed09cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c8f6f25e-92d3-40de-8090-64f802d0b431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1641:0</value>
      <webElementGuid>56379126-897f-4575-9ff6-8aa08930606b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>0806f6dd-4085-4c0b-bc86-17d0cb27023d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectedAll</value>
      <webElementGuid>cc9155f2-90d6-4d40-baa7-f2e08434b130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;virtualAutocompleteListbox_7c1887c26ee74&quot;)/li[@class=&quot;slds-dropdown__item has-icon--left   forceVirtualAutocompleteMenuOption&quot;]/a[1]</value>
      <webElementGuid>f86c7b80-79e0-46ce-9bea-a63b9ca2c84b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='virtualAutocompleteListbox_7c1887c26ee74']/li[2]/a</value>
      <webElementGuid>c95addd7-b99b-41e5-8632-50e4dc21e982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Views'])[1]/following::a[1]</value>
      <webElementGuid>601e74c2-3496-4a5e-8b0d-4da38e5b365c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[2]/following::a[1]</value>
      <webElementGuid>2f4db669-479d-4ad2-bc13-c46edf410c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[13]</value>
      <webElementGuid>0dae9bcf-73c8-426d-8479-2cfc66100cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a</value>
      <webElementGuid>e0050149-66e1-4f9a-b5ec-8cd2ebca3a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'SelectedAll' or . = 'SelectedAll')]</value>
      <webElementGuid>2d72940c-7519-46c4-970b-f1297b0725d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
