<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__End Date</name>
   <tag></tag>
   <elementGuidId>4d6efffd-6dae-4c96-9b9f-6a61ea555c82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-184</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//lightning-datepicker/div//input[@name=&quot;End Date&quot;]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a929e22-b176-4c4d-a6d2-478d37d1f95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>c925298c-8f33-4af3-b82a-00bc9782fa11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fd33db5-ce61-4016-bc35-28d5d6594cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-184</value>
      <webElementGuid>89ab4ba3-3832-42dc-97d7-5781a2d7411f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46cb3df3-918d-421d-b101-4ef56caf402a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>End Date</value>
      <webElementGuid>23a016ae-cc2e-468b-8ff8-81ee16fef8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d77261c2-86a7-4dde-b8ee-968009c9484f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>fmt-text-184</value>
      <webElementGuid>a1557fae-5f05-4130-9f91-154f86ff67e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-184&quot;)</value>
      <webElementGuid>3d1dffe3-fb82-4dd4-9912-e35f82876b5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-184']</value>
      <webElementGuid>f8be1bb9-7445-40e5-8d11-cf79e7ab098e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-input[@id='end-date-171']/lightning-datepicker/div/div/input</value>
      <webElementGuid>529b1487-6f9d-4c32-b5cd-47c8136bf6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-input/lightning-datepicker/div/div/input</value>
      <webElementGuid>ff576c6d-5427-4d9d-80af-03ceac4b493e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-184' and @name = 'End Date']</value>
      <webElementGuid>ed202e83-9b99-49bc-9bf4-b3075c90e3aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
