<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Leave</name>
   <tag></tag>
   <elementGuidId>c34982d5-b9eb-468a-8907-446acbce4494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b9bd1f5-e4ff-42b5-8123-50fccb1e6a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>65b9252d-0032-41c6-8168-2ca208aff226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>7b6bf3f2-34ae-480b-ad84-eec935f190f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CRMITCommunity/s/applyleave</value>
      <webElementGuid>fe3c9f3c-2d67-4784-8928-4b069b5f7d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comm-navigation__top-level-item-link js-top-level-menu-item linkBtn</value>
      <webElementGuid>98047f13-b43d-40c1-9bfb-f24b5971c4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>50:137;a</value>
      <webElementGuid>84675b1f-d679-44ba-a367-0d9445af51e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Leave</value>
      <webElementGuid>f0efde65-1896-476f-bf45-46f6396e6f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9&quot;)</value>
      <webElementGuid>d3039b02-34d0-4d4d-8ec3-d6b8b44f8345</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='9']</value>
      <webElementGuid>d7953bf3-f044-4db6-872d-0c71fe4f6901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commThemeNav']/div/div/nav/ul/li[10]/a</value>
      <webElementGuid>9d731e46-1a25-4723-aff2-2fa4d3ee7003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Leave')]</value>
      <webElementGuid>4534594e-dd80-4a28-b541-cc33a2e9a177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Attendance Records'])[1]/following::a[1]</value>
      <webElementGuid>33f520b1-4e1a-40de-90b7-b3709895740b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Attendance'])[1]/following::a[2]</value>
      <webElementGuid>750d0e08-8615-423b-ab11-5f97a932dd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>4ad32329-c7b6-4858-ae3c-2a7fdf6c4a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pit Stop'])[1]/preceding::a[2]</value>
      <webElementGuid>1ca54b09-7d88-4094-a2f4-8fb162f50688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Leave']/parent::*</value>
      <webElementGuid>1370ff98-276a-45bd-8f44-7271b02f611e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/CRMITCommunity/s/applyleave')]</value>
      <webElementGuid>47e1c6b3-efc6-4f14-b34d-af45d9d91429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>c5ad88ff-e117-4e9c-a29a-ec1657d49b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '9' and @href = '/CRMITCommunity/s/applyleave' and (text() = 'My Leave' or . = 'My Leave')]</value>
      <webElementGuid>ef93ed6f-2410-44ea-9858-d56ad08bac4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
