<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Attendance Records</name>
   <tag></tag>
   <elementGuidId>a79e71cb-6b99-448f-86bb-f3cba260c491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>070174cb-d752-4be1-8842-d61f7531b778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>86f96a45-640e-4b6a-9e65-274ae978b237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a2ae179e-4c88-4728-80ed-8fd9f790dff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CRMITCommunity/s/attendance/Attendance__c/00B1K00000ANJ7KUAX</value>
      <webElementGuid>ad762d33-e429-4f54-a43d-c13dc05138ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comm-navigation__top-level-item-link js-top-level-menu-item linkBtn</value>
      <webElementGuid>950a0a26-5090-4ad4-a557-c35780f4d8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>45:146;a</value>
      <webElementGuid>58151866-e9b6-4823-a3f7-af9d98b85994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Attendance Records</value>
      <webElementGuid>12f17726-a181-4389-be77-e1fd26112cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8&quot;)</value>
      <webElementGuid>9e0fbd5f-ed4d-4c48-95aa-a049ad8d0ca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='8']</value>
      <webElementGuid>0c017223-817b-4499-a8e9-bf7f543011d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commThemeNav']/div/div/nav/ul/li[9]/a</value>
      <webElementGuid>4b0bec4d-dec1-45c9-ac89-74a38cac1a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Attendance Records')]</value>
      <webElementGuid>a5e4e3a7-b6ec-4a9e-b743-62428be4cfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Attendance'])[1]/following::a[1]</value>
      <webElementGuid>8c3638d8-0820-41ea-99d5-9f04e6778ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Expense Claims(Zoho)'])[1]/following::a[2]</value>
      <webElementGuid>96b79fa7-ca89-4e6e-a01b-cdb889bcb7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>9f9e8c10-92f6-4142-93b3-58d8a2e86109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Leave'])[1]/preceding::a[2]</value>
      <webElementGuid>e34f1d8f-b9c8-4d80-b904-19a7fedb326b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Attendance Records']/parent::*</value>
      <webElementGuid>2c1c5d2a-fd80-4bc0-997c-cb1e9927fbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/CRMITCommunity/s/attendance/Attendance__c/00B1K00000ANJ7KUAX')]</value>
      <webElementGuid>2c06875f-fdb3-4d87-a97a-c355ff5f7884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>437c3e9d-4357-4bd7-a96b-17e32ae6d5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '8' and @href = '/CRMITCommunity/s/attendance/Attendance__c/00B1K00000ANJ7KUAX' and (text() = 'My Attendance Records' or . = 'My Attendance Records')]</value>
      <webElementGuid>0603471c-cb8c-44d4-b4ab-2641e9bc9350</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
